/*
 * Sourcecode berikut terbuka untuk umum
 * Semua orang diperkenankan memanfaatkan kode ini
 * Tanpa dipungut biaya apapun alias gratis
 * Akan tetapi segala resiko tanggung sendiri
 * Happy coding...
 */

/*
 * KonversiSuhu.java
 *
 * Created on 04 Apr 09, 20:56:47
 */

package TampilanSuhu;

/**
 *
 * @author farazinux
 */
public class KonversiSuhu extends javax.swing.JFrame {

    /** Creates new form KonversiSuhu */
    public KonversiSuhu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuhu1 = new TampilanSuhu.PanelSuhu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(panelSuhu1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KonversiSuhu konversisuhu = new KonversiSuhu();
                konversisuhu.setTitle("Konversi Suhu Dunia");
                konversisuhu.setLocationRelativeTo(null);
                konversisuhu.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private TampilanSuhu.PanelSuhu panelSuhu1;
    // End of variables declaration//GEN-END:variables

}
